"""Add DispositivoBiometrico

Revision ID: 02d340003dc6
Revises: b4e07eaf3dad
Create Date: 2026-06-06 14:43:10.417629

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "02d340003dc6"
down_revision: Union[str, Sequence[str], None] = "b4e07eaf3dad"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
