"""Add nomina fields and periodicidad

Revision ID: 0470b63eec00
Revises: 072d4a747771
Create Date: 2026-06-10 15:27:00.227309

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0470b63eec00"
down_revision: Union[str, Sequence[str], None] = "072d4a747771"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # conceptos_nomina
    op.add_column("conceptos_nomina", sa.Column("clave_sat", sa.String(length=10), nullable=True))
    op.add_column("conceptos_nomina", sa.Column("tipo_sat", sa.String(length=1), nullable=True))
    op.add_column(
        "conceptos_nomina",
        sa.Column("es_exento", sa.Boolean(), nullable=False, server_default="false"),
    )
    op.add_column(
        "conceptos_nomina",
        sa.Column("es_obligatorio", sa.Boolean(), nullable=False, server_default="false"),
    )
    # detalles_nomina
    op.add_column(
        "detalles_nomina", sa.Column("descripcion_extra", sa.String(length=200), nullable=True)
    )
    # empleados
    op.add_column(
        "empleados", sa.Column("periodicidad_nomina", sa.String(length=20), nullable=True)
    )
    op.add_column(
        "empleados", sa.Column("numero_seguro_social", sa.String(length=11), nullable=True)
    )
    # info_empresa
    op.add_column("info_empresa", sa.Column("nombre", sa.String(length=200), nullable=True))
    op.add_column("info_empresa", sa.Column("rfc", sa.String(length=13), nullable=True))
    op.add_column("info_empresa", sa.Column("regimen_fiscal", sa.String(length=100), nullable=True))
    op.add_column("info_empresa", sa.Column("cp_fiscal", sa.String(length=10), nullable=True))
    op.add_column(
        "info_empresa",
        sa.Column(
            "periodicidad_nomina", sa.String(length=20), nullable=False, server_default="Quincenal"
        ),
    )
    # lotes_nomina
    op.add_column("lotes_nomina", sa.Column("descripcion", sa.String(length=200), nullable=True))
    op.add_column(
        "lotes_nomina",
        sa.Column("periodicidad", sa.String(length=20), nullable=False, server_default="Quincenal"),
    )
    op.add_column("lotes_nomina", sa.Column("numero_periodo", sa.Integer(), nullable=True))
    op.add_column("lotes_nomina", sa.Column("año", sa.Integer(), nullable=True))
    op.add_column(
        "lotes_nomina",
        sa.Column("numero_empleados", sa.Integer(), nullable=False, server_default="0"),
    )
    op.add_column(
        "lotes_nomina",
        sa.Column(
            "total_percepciones",
            sa.Numeric(precision=15, scale=2),
            nullable=False,
            server_default="0.00",
        ),
    )
    op.add_column(
        "lotes_nomina",
        sa.Column(
            "total_deducciones",
            sa.Numeric(precision=15, scale=2),
            nullable=False,
            server_default="0.00",
        ),
    )
    op.add_column(
        "lotes_nomina",
        sa.Column(
            "total_neto", sa.Numeric(precision=15, scale=2), nullable=False, server_default="0.00"
        ),
    )
    # nominas
    op.add_column(
        "nominas",
        sa.Column("periodicidad", sa.String(length=20), nullable=False, server_default="Quincenal"),
    )
    op.add_column(
        "nominas",
        sa.Column(
            "subtotal_percepciones",
            sa.Numeric(precision=10, scale=2),
            nullable=False,
            server_default="0.00",
        ),
    )
    op.add_column(
        "nominas",
        sa.Column(
            "subtotal_deducciones",
            sa.Numeric(precision=10, scale=2),
            nullable=False,
            server_default="0.00",
        ),
    )
    op.add_column(
        "nominas",
        sa.Column(
            "subtotal_otros",
            sa.Numeric(precision=10, scale=2),
            nullable=False,
            server_default="0.00",
        ),
    )
    op.add_column(
        "nominas",
        sa.Column(
            "neto_pagar", sa.Numeric(precision=10, scale=2), nullable=False, server_default="0.00"
        ),
    )
    op.add_column("nominas", sa.Column("xml_cfdi_content", sa.Text(), nullable=True))
    op.add_column("nominas", sa.Column("observaciones", sa.String(), nullable=True))
    # prestamos
    op.add_column("prestamos", sa.Column("fecha_inicio", sa.Date(), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("prestamos", "fecha_inicio")
    op.drop_column("nominas", "observaciones")
    op.drop_column("nominas", "xml_cfdi_content")
    op.drop_column("nominas", "neto_pagar")
    op.drop_column("nominas", "subtotal_otros")
    op.drop_column("nominas", "subtotal_deducciones")
    op.drop_column("nominas", "subtotal_percepciones")
    op.drop_column("nominas", "periodicidad")
    op.drop_column("lotes_nomina", "total_neto")
    op.drop_column("lotes_nomina", "total_deducciones")
    op.drop_column("lotes_nomina", "total_percepciones")
    op.drop_column("lotes_nomina", "numero_empleados")
    op.drop_column("lotes_nomina", "año")
    op.drop_column("lotes_nomina", "numero_periodo")
    op.drop_column("lotes_nomina", "periodicidad")
    op.drop_column("lotes_nomina", "descripcion")
    op.drop_column("info_empresa", "periodicidad_nomina")
    op.drop_column("info_empresa", "cp_fiscal")
    op.drop_column("info_empresa", "regimen_fiscal")
    op.drop_column("info_empresa", "rfc")
    op.drop_column("info_empresa", "nombre")
    op.drop_column("empleados", "numero_seguro_social")
    op.drop_column("empleados", "periodicidad_nomina")
    op.drop_column("detalles_nomina", "descripcion_extra")
    op.drop_column("conceptos_nomina", "es_obligatorio")
    op.drop_column("conceptos_nomina", "es_exento")
    op.drop_column("conceptos_nomina", "tipo_sat")
    op.drop_column("conceptos_nomina", "clave_sat")
    # ### end Alembic commands ###
