"""Add ConfiguracionDashboard

Revision ID: 072d4a747771
Revises: 859ea593669c
Create Date: 2026-06-10 14:49:31.821048

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "072d4a747771"
down_revision: Union[str, Sequence[str], None] = "859ea593669c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "configuracion_dashboard",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("empleado_id", sa.Integer(), nullable=False),
        sa.Column("layout_json", sa.JSON(), nullable=False),
        sa.Column("creado_en", sa.DateTime(), nullable=False),
        sa.Column("actualizado_en", sa.DateTime(), nullable=False),
        sa.Column("activo", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["empleado_id"], ["empleados.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("empleado_id"),
    )
    op.create_index(
        op.f("ix_configuracion_dashboard_id"), "configuracion_dashboard", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_configuracion_dashboard_id"), table_name="configuracion_dashboard")
    op.drop_table("configuracion_dashboard")
    # ### end Alembic commands ###
