"""add reporta_a_puesto_id to puestos

Revision ID: 1f5ce9a03bfd
Revises: c059ad856719
Create Date: 2026-06-05 02:24:08.289915

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1f5ce9a03bfd"
down_revision: Union[str, Sequence[str], None] = "c059ad856719"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        "fk_area_jefe",
        "areas",
        "empleados",
        ["jefe_area_id"],
        ["id"],
        ondelete="SET NULL",
        use_alter=True,
    )
    op.add_column("puestos", sa.Column("reporta_a_puesto_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        None, "puestos", "puestos", ["reporta_a_puesto_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "puestos", type_="foreignkey")
    op.drop_column("puestos", "reporta_a_puesto_id")
    op.drop_constraint("fk_area_jefe", "areas", type_="foreignkey")
    # ### end Alembic commands ###
