"""Add infonavit and umi

Revision ID: 26eefb55c8d9
Revises: 20fd1473a755
Create Date: 2026-06-16 03:32:26.277537

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "26eefb55c8d9"
down_revision: Union[str, Sequence[str], None] = "20fd1473a755"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "empleados", sa.Column("infonavit_tipo_descuento", sa.String(length=50), nullable=True)
    )
    op.add_column(
        "empleados",
        sa.Column("infonavit_valor_descuento", sa.Numeric(precision=10, scale=4), nullable=True),
    )
    op.add_column(
        "parametros_fiscales", sa.Column("umi", sa.Numeric(precision=10, scale=4), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("parametros_fiscales", "umi")
    op.drop_column("empleados", "infonavit_valor_descuento")
    op.drop_column("empleados", "infonavit_tipo_descuento")
    # ### end Alembic commands ###
