"""Add CampaniaEvaluacion and evaluador_id

Revision ID: 2950dcd992f6
Revises: 75a00da9c91b
Create Date: 2026-06-10 23:39:52.161526

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2950dcd992f6"
down_revision: Union[str, Sequence[str], None] = "75a00da9c91b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "campania_evaluacion",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nombre", sa.String(length=100), nullable=False),
        sa.Column("fecha_inicio", sa.Date(), nullable=False),
        sa.Column("fecha_fin", sa.Date(), nullable=False),
        sa.Column("activa", sa.Boolean(), nullable=True),
        sa.Column("creado_en", sa.DateTime(), nullable=False),
        sa.Column("actualizado_en", sa.DateTime(), nullable=False),
        sa.Column("activo", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_campania_evaluacion_id"), "campania_evaluacion", ["id"], unique=False)
    op.add_column("respuestas_evaluacion", sa.Column("campania_id", sa.Integer(), nullable=True))
    op.add_column("respuestas_evaluacion", sa.Column("evaluador_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        None, "respuestas_evaluacion", "empleados", ["evaluador_id"], ["id"], ondelete="SET NULL"
    )
    op.create_foreign_key(
        None,
        "respuestas_evaluacion",
        "campania_evaluacion",
        ["campania_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "respuestas_evaluacion", type_="foreignkey")
    op.drop_constraint(None, "respuestas_evaluacion", type_="foreignkey")
    op.drop_column("respuestas_evaluacion", "evaluador_id")
    op.drop_column("respuestas_evaluacion", "campania_id")
    op.drop_index(op.f("ix_campania_evaluacion_id"), table_name="campania_evaluacion")
    op.drop_table("campania_evaluacion")
    # ### end Alembic commands ###
