"""Asistencia_horarios_comidas

Revision ID: 31fc2c50bf4e
Revises: e9d26e2f7b4e
Create Date: 2026-06-13 20:46:37.777572

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "31fc2c50bf4e"
down_revision: Union[str, Sequence[str], None] = "e9d26e2f7b4e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "asistencias", sa.Column("hora_salida_descanso", sa.String(length=5), nullable=True)
    )
    op.add_column(
        "asistencias", sa.Column("hora_entrada_descanso", sa.String(length=5), nullable=True)
    )
    op.add_column(
        "asistencias",
        sa.Column("tiempo_efectivo_minutos", sa.Integer(), nullable=False, server_default="0"),
    )
    op.add_column(
        "empleados",
        sa.Column("turno_entrada", sa.String(length=5), nullable=False, server_default="09:00"),
    )
    op.add_column(
        "empleados",
        sa.Column("turno_salida", sa.String(length=5), nullable=False, server_default="18:00"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("empleados", "turno_salida")
    op.drop_column("empleados", "turno_entrada")
    op.drop_column("asistencias", "tiempo_efectivo_minutos")
    op.drop_column("asistencias", "hora_entrada_descanso")
    op.drop_column("asistencias", "hora_salida_descanso")
    # ### end Alembic commands ###
