"""Add auditoria mixin columns

Revision ID: 4f51cb1c3911
Revises: 31fc2c50bf4e
Create Date: 2026-06-14 06:08:01.070918

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4f51cb1c3911"
down_revision: Union[str, Sequence[str], None] = "31fc2c50bf4e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("areas", sa.Column("creado_por_id", sa.Integer(), nullable=True))
    op.add_column("areas", sa.Column("actualizado_por_id", sa.Integer(), nullable=True))
    op.add_column("asistencias", sa.Column("creado_por_id", sa.Integer(), nullable=True))
    op.add_column("asistencias", sa.Column("actualizado_por_id", sa.Integer(), nullable=True))
    op.add_column("campania_clima", sa.Column("creado_por_id", sa.Integer(), nullable=True))
    op.add_column("campania_clima", sa.Column("actualizado_por_id", sa.Integer(), nullable=True))
    op.add_column("campania_evaluacion", sa.Column("creado_por_id", sa.Integer(), nullable=True))
    op.add_column(
        "campania_evaluacion", sa.Column("actualizado_por_id", sa.Integer(), nullable=True)
    )
    op.add_column("candidatos", sa.Column("creado_por_id", sa.Integer(), nullable=True))
    op.add_column("candidatos", sa.Column("actualizado_por_id", sa.Integer(), nullable=True))
    op.add_column("conceptos_nomina", sa.Column("creado_por_id", sa.Integer(), nullable=True))
    op.add_column("conceptos_nomina", sa.Column("actualizado_por_id", sa.Integer(), nullable=True))
    op.add_column(
        "configuracion_dashboard", sa.Column("creado_por_id", sa.Integer(), nullable=True)
    )
    op.add_column(
        "configuracion_dashboard", sa.Column("actualizado_por_id", sa.Integer(), nullable=True)
    )
    op.add_column(
        "conversacion_participantes", sa.Column("creado_por_id", sa.Integer(), nullable=True)
    )
    op.add_column(
        "conversacion_participantes", sa.Column("actualizado_por_id", sa.Integer(), nullable=True)
    )
    op.add_column("conversaciones", sa.Column("actualizado_por_id", sa.Integer(), nullable=True))
    op.add_column("credenciales", sa.Column("creado_por_id", sa.Integer(), nullable=True))
    op.add_column("credenciales", sa.Column("actualizado_por_id", sa.Integer(), nullable=True))
    op.add_column("cyi_progreso", sa.Column("creado_por_id", sa.Integer(), nullable=True))
    op.add_column("cyi_progreso", sa.Column("actualizado_por_id", sa.Integer(), nullable=True))
    op.add_column("delegacion_roles", sa.Column("creado_por_id", sa.Integer(), nullable=True))
    op.add_column("delegacion_roles", sa.Column("actualizado_por_id", sa.Integer(), nullable=True))
    op.add_column("detalles_nomina", sa.Column("creado_por_id", sa.Integer(), nullable=True))
    op.add_column("detalles_nomina", sa.Column("actualizado_por_id", sa.Integer(), nullable=True))
    op.add_column("dias_festivos", sa.Column("creado_por_id", sa.Integer(), nullable=True))
    op.add_column("dias_festivos", sa.Column("actualizado_por_id", sa.Integer(), nullable=True))
    op.add_column("empleado_permisos", sa.Column("creado_por_id", sa.Integer(), nullable=True))
    op.add_column("empleado_permisos", sa.Column("actualizado_por_id", sa.Integer(), nullable=True))
    op.add_column("empleados", sa.Column("creado_por_id", sa.Integer(), nullable=True))
    op.add_column("empleados", sa.Column("actualizado_por_id", sa.Integer(), nullable=True))
    op.add_column("empleados_familiar", sa.Column("creado_por_id", sa.Integer(), nullable=True))
    op.add_column(
        "empleados_familiar", sa.Column("actualizado_por_id", sa.Integer(), nullable=True)
    )
    op.add_column("empleados_salud", sa.Column("creado_por_id", sa.Integer(), nullable=True))
    op.add_column("empleados_salud", sa.Column("actualizado_por_id", sa.Integer(), nullable=True))
    op.add_column("evaluaciones", sa.Column("creado_por_id", sa.Integer(), nullable=True))
    op.add_column("evaluaciones", sa.Column("actualizado_por_id", sa.Integer(), nullable=True))
    op.add_column("evento_participantes", sa.Column("creado_por_id", sa.Integer(), nullable=True))
    op.add_column(
        "evento_participantes", sa.Column("actualizado_por_id", sa.Integer(), nullable=True)
    )
    op.add_column("eventos_empresa", sa.Column("actualizado_por_id", sa.Integer(), nullable=True))
    op.add_column("incidencias", sa.Column("creado_por_id", sa.Integer(), nullable=True))
    op.add_column("incidencias", sa.Column("actualizado_por_id", sa.Integer(), nullable=True))
    op.add_column("lotes_nomina", sa.Column("actualizado_por_id", sa.Integer(), nullable=True))
    op.add_column("mensajes", sa.Column("creado_por_id", sa.Integer(), nullable=True))
    op.add_column("mensajes", sa.Column("actualizado_por_id", sa.Integer(), nullable=True))
    op.add_column("nominas", sa.Column("creado_por_id", sa.Integer(), nullable=True))
    op.add_column("nominas", sa.Column("actualizado_por_id", sa.Integer(), nullable=True))
    op.add_column("notificaciones", sa.Column("creado_por_id", sa.Integer(), nullable=True))
    op.add_column("notificaciones", sa.Column("actualizado_por_id", sa.Integer(), nullable=True))
    op.add_column("permisos", sa.Column("creado_por_id", sa.Integer(), nullable=True))
    op.add_column("permisos", sa.Column("actualizado_por_id", sa.Integer(), nullable=True))
    op.add_column("permisos_campo", sa.Column("creado_por_id", sa.Integer(), nullable=True))
    op.add_column("permisos_campo", sa.Column("actualizado_por_id", sa.Integer(), nullable=True))
    op.add_column("pregunta_clima", sa.Column("creado_por_id", sa.Integer(), nullable=True))
    op.add_column("pregunta_clima", sa.Column("actualizado_por_id", sa.Integer(), nullable=True))
    op.add_column("prestamos", sa.Column("creado_por_id", sa.Integer(), nullable=True))
    op.add_column("prestamos", sa.Column("actualizado_por_id", sa.Integer(), nullable=True))
    op.add_column("puestos", sa.Column("creado_por_id", sa.Integer(), nullable=True))
    op.add_column("puestos", sa.Column("actualizado_por_id", sa.Integer(), nullable=True))
    op.add_column("recursos", sa.Column("creado_por_id", sa.Integer(), nullable=True))
    op.add_column("recursos", sa.Column("actualizado_por_id", sa.Integer(), nullable=True))
    op.add_column("registros_checador", sa.Column("creado_por_id", sa.Integer(), nullable=True))
    op.add_column(
        "registros_checador", sa.Column("actualizado_por_id", sa.Integer(), nullable=True)
    )
    op.add_column("respuesta_clima", sa.Column("creado_por_id", sa.Integer(), nullable=True))
    op.add_column("respuesta_clima", sa.Column("actualizado_por_id", sa.Integer(), nullable=True))
    op.add_column("respuestas_evaluacion", sa.Column("creado_por_id", sa.Integer(), nullable=True))
    op.add_column(
        "respuestas_evaluacion", sa.Column("actualizado_por_id", sa.Integer(), nullable=True)
    )
    op.add_column("rol_permisos", sa.Column("creado_por_id", sa.Integer(), nullable=True))
    op.add_column("rol_permisos", sa.Column("actualizado_por_id", sa.Integer(), nullable=True))
    op.add_column("roles", sa.Column("creado_por_id", sa.Integer(), nullable=True))
    op.add_column("roles", sa.Column("actualizado_por_id", sa.Integer(), nullable=True))
    op.add_column("tareas", sa.Column("creado_por_id", sa.Integer(), nullable=True))
    op.add_column("tareas", sa.Column("actualizado_por_id", sa.Integer(), nullable=True))
    op.add_column("vacaciones", sa.Column("creado_por_id", sa.Integer(), nullable=True))
    op.add_column("vacaciones", sa.Column("actualizado_por_id", sa.Integer(), nullable=True))
    op.add_column("vacantes", sa.Column("creado_por_id", sa.Integer(), nullable=True))
    op.add_column("vacantes", sa.Column("actualizado_por_id", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("vacantes", "actualizado_por_id")
    op.drop_column("vacantes", "creado_por_id")
    op.drop_column("vacaciones", "actualizado_por_id")
    op.drop_column("vacaciones", "creado_por_id")
    op.drop_column("tareas", "actualizado_por_id")
    op.drop_column("tareas", "creado_por_id")
    op.drop_column("roles", "actualizado_por_id")
    op.drop_column("roles", "creado_por_id")
    op.drop_column("rol_permisos", "actualizado_por_id")
    op.drop_column("rol_permisos", "creado_por_id")
    op.drop_column("respuestas_evaluacion", "actualizado_por_id")
    op.drop_column("respuestas_evaluacion", "creado_por_id")
    op.drop_column("respuesta_clima", "actualizado_por_id")
    op.drop_column("respuesta_clima", "creado_por_id")
    op.drop_column("registros_checador", "actualizado_por_id")
    op.drop_column("registros_checador", "creado_por_id")
    op.drop_column("recursos", "actualizado_por_id")
    op.drop_column("recursos", "creado_por_id")
    op.drop_column("puestos", "actualizado_por_id")
    op.drop_column("puestos", "creado_por_id")
    op.drop_column("prestamos", "actualizado_por_id")
    op.drop_column("prestamos", "creado_por_id")
    op.drop_column("pregunta_clima", "actualizado_por_id")
    op.drop_column("pregunta_clima", "creado_por_id")
    op.drop_column("permisos_campo", "actualizado_por_id")
    op.drop_column("permisos_campo", "creado_por_id")
    op.drop_column("permisos", "actualizado_por_id")
    op.drop_column("permisos", "creado_por_id")
    op.drop_column("notificaciones", "actualizado_por_id")
    op.drop_column("notificaciones", "creado_por_id")
    op.drop_column("nominas", "actualizado_por_id")
    op.drop_column("nominas", "creado_por_id")
    op.drop_column("mensajes", "actualizado_por_id")
    op.drop_column("mensajes", "creado_por_id")
    op.drop_column("lotes_nomina", "actualizado_por_id")
    op.drop_column("incidencias", "actualizado_por_id")
    op.drop_column("incidencias", "creado_por_id")
    op.drop_column("eventos_empresa", "actualizado_por_id")
    op.drop_column("evento_participantes", "actualizado_por_id")
    op.drop_column("evento_participantes", "creado_por_id")
    op.drop_column("evaluaciones", "actualizado_por_id")
    op.drop_column("evaluaciones", "creado_por_id")
    op.drop_column("empleados_salud", "actualizado_por_id")
    op.drop_column("empleados_salud", "creado_por_id")
    op.drop_column("empleados_familiar", "actualizado_por_id")
    op.drop_column("empleados_familiar", "creado_por_id")
    op.drop_column("empleados", "actualizado_por_id")
    op.drop_column("empleados", "creado_por_id")
    op.drop_column("empleado_permisos", "actualizado_por_id")
    op.drop_column("empleado_permisos", "creado_por_id")
    op.drop_column("dias_festivos", "actualizado_por_id")
    op.drop_column("dias_festivos", "creado_por_id")
    op.drop_column("detalles_nomina", "actualizado_por_id")
    op.drop_column("detalles_nomina", "creado_por_id")
    op.drop_column("delegacion_roles", "actualizado_por_id")
    op.drop_column("delegacion_roles", "creado_por_id")
    op.drop_column("cyi_progreso", "actualizado_por_id")
    op.drop_column("cyi_progreso", "creado_por_id")
    op.drop_column("credenciales", "actualizado_por_id")
    op.drop_column("credenciales", "creado_por_id")
    op.drop_column("conversaciones", "actualizado_por_id")
    op.drop_column("conversacion_participantes", "actualizado_por_id")
    op.drop_column("conversacion_participantes", "creado_por_id")
    op.drop_column("configuracion_dashboard", "actualizado_por_id")
    op.drop_column("configuracion_dashboard", "creado_por_id")
    op.drop_column("conceptos_nomina", "actualizado_por_id")
    op.drop_column("conceptos_nomina", "creado_por_id")
    op.drop_column("candidatos", "actualizado_por_id")
    op.drop_column("candidatos", "creado_por_id")
    op.drop_column("campania_evaluacion", "actualizado_por_id")
    op.drop_column("campania_evaluacion", "creado_por_id")
    op.drop_column("campania_clima", "actualizado_por_id")
    op.drop_column("campania_clima", "creado_por_id")
    op.drop_column("asistencias", "actualizado_por_id")
    op.drop_column("asistencias", "creado_por_id")
    op.drop_column("areas", "actualizado_por_id")
    op.drop_column("areas", "creado_por_id")
    # ### end Alembic commands ###
