"""Add parametros fiscales table

Revision ID: 6f05c40649af
Revises: 4f51cb1c3911
Create Date: 2026-06-14 07:46:30.955633

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6f05c40649af"
down_revision: Union[str, Sequence[str], None] = "4f51cb1c3911"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "parametros_fiscales",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ejercicio", sa.Integer(), nullable=False),
        sa.Column("uma", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("salario_minimo_general", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("salario_minimo_frontera", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("tabla_isr_mensual", sa.String(), nullable=False),
        sa.Column("creado_en", sa.DateTime(), nullable=False),
        sa.Column("actualizado_en", sa.DateTime(), nullable=False),
        sa.Column("creado_por_id", sa.Integer(), nullable=True),
        sa.Column("actualizado_por_id", sa.Integer(), nullable=True),
        sa.Column("activo", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_parametros_fiscales_ejercicio"), "parametros_fiscales", ["ejercicio"], unique=True
    )
    op.create_index(op.f("ix_parametros_fiscales_id"), "parametros_fiscales", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_parametros_fiscales_id"), table_name="parametros_fiscales")
    op.drop_index(op.f("ix_parametros_fiscales_ejercicio"), table_name="parametros_fiscales")
    op.drop_table("parametros_fiscales")
    # ### end Alembic commands ###
