"""Add Clima Laboral dynamic models

Revision ID: 75a00da9c91b
Revises: 0470b63eec00
Create Date: 2026-06-10 19:37:21.146393

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "75a00da9c91b"
down_revision: Union[str, Sequence[str], None] = "0470b63eec00"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "campania_clima",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nombre", sa.String(length=100), nullable=False),
        sa.Column("fecha_inicio", sa.Date(), nullable=False),
        sa.Column("fecha_fin", sa.Date(), nullable=False),
        sa.Column("activa", sa.Boolean(), nullable=True),
        sa.Column("creado_en", sa.DateTime(), nullable=False),
        sa.Column("actualizado_en", sa.DateTime(), nullable=False),
        sa.Column("activo", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_campania_clima_id"), "campania_clima", ["id"], unique=False)
    op.create_table(
        "pregunta_clima",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("categoria", sa.String(length=100), nullable=False),
        sa.Column("pregunta", sa.String(), nullable=False),
        sa.Column("creado_en", sa.DateTime(), nullable=False),
        sa.Column("actualizado_en", sa.DateTime(), nullable=False),
        sa.Column("activo", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_pregunta_clima_id"), "pregunta_clima", ["id"], unique=False)
    op.create_table(
        "respuesta_clima",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("campania_id", sa.Integer(), nullable=False),
        sa.Column("empleado_id", sa.Integer(), nullable=False),
        sa.Column("nivel_jerarquico", sa.String(length=50), nullable=True),
        sa.Column("ubicacion", sa.String(length=50), nullable=True),
        sa.Column("respuestas_json", sa.JSON(), nullable=False),
        sa.Column("creado_en", sa.DateTime(), nullable=False),
        sa.Column("actualizado_en", sa.DateTime(), nullable=False),
        sa.Column("activo", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["campania_id"], ["campania_clima.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["empleado_id"], ["empleados.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_respuesta_clima_id"), "respuesta_clima", ["id"], unique=False)
    op.drop_index(op.f("ix_encuesta_clima_id"), table_name="encuesta_clima")
    op.drop_table("encuesta_clima")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "encuesta_clima",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("empleado_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("nivel_jerarquico", sa.VARCHAR(length=50), autoincrement=False, nullable=True),
        sa.Column("ubicacion", sa.VARCHAR(length=50), autoincrement=False, nullable=True),
        sa.Column("hijos", sa.VARCHAR(length=20), autoincrement=False, nullable=True),
        sa.Column("antiguedad", sa.VARCHAR(length=20), autoincrement=False, nullable=True),
        sa.Column("genero", sa.VARCHAR(length=20), autoincrement=False, nullable=True),
        sa.Column(
            "orientacion_org",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "admin_talento",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "estilo_direccion",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "comunicacion_int",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "trabajo_equipo",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "capacidad_prof",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "medio_ambiente",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("creado_en", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column("actualizado_en", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column("activo", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["empleado_id"],
            ["empleados.id"],
            name=op.f("encuesta_clima_empleado_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("encuesta_clima_pkey")),
        sa.UniqueConstraint(
            "empleado_id",
            name=op.f("encuesta_clima_empleado_id_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(op.f("ix_encuesta_clima_id"), "encuesta_clima", ["id"], unique=False)
    op.drop_index(op.f("ix_respuesta_clima_id"), table_name="respuesta_clima")
    op.drop_table("respuesta_clima")
    op.drop_index(op.f("ix_pregunta_clima_id"), table_name="pregunta_clima")
    op.drop_table("pregunta_clima")
    op.drop_index(op.f("ix_campania_clima_id"), table_name="campania_clima")
    op.drop_table("campania_clima")
    # ### end Alembic commands ###
