"""add hierarchy_level

Revision ID: 81e97e551021
Revises: 42610dae7cc3
Create Date: 2026-06-14 10:15:53.746881

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "81e97e551021"
down_revision: Union[str, Sequence[str], None] = "42610dae7cc3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("puestos", sa.Column("hierarchy_level", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("puestos", "hierarchy_level")
    # ### end Alembic commands ###
