"""Add politicas_vacacionales

Revision ID: 8271af7b0cff
Revises: 59ae4d89c76b
Create Date: 2026-06-19 18:35:24.209524

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8271af7b0cff"
down_revision: Union[str, Sequence[str], None] = "59ae4d89c76b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "politicas_vacacionales",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("anios_desde", sa.Integer(), nullable=False),
        sa.Column("anios_hasta", sa.Integer(), nullable=False),
        sa.Column("dias_otorgados", sa.Integer(), nullable=False),
        sa.Column("creado_en", sa.DateTime(), nullable=False),
        sa.Column("actualizado_en", sa.DateTime(), nullable=False),
        sa.Column("creado_por_id", sa.Integer(), nullable=True),
        sa.Column("actualizado_por_id", sa.Integer(), nullable=True),
        sa.Column("activo", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_politicas_vacacionales_id"), "politicas_vacacionales", ["id"], unique=False
    )
    # ### end Alembic commands ###
    from datetime import datetime

    op.bulk_insert(
        sa.table(
            "politicas_vacacionales",
            sa.column("anios_desde", sa.Integer),
            sa.column("anios_hasta", sa.Integer),
            sa.column("dias_otorgados", sa.Integer),
            sa.column("creado_en", sa.DateTime),
            sa.column("actualizado_en", sa.DateTime),
            sa.column("activo", sa.Boolean),
        ),
        [
            {
                "anios_desde": 1,
                "anios_hasta": 1,
                "dias_otorgados": 12,
                "creado_en": datetime.utcnow(),
                "actualizado_en": datetime.utcnow(),
                "activo": True,
            },
            {
                "anios_desde": 2,
                "anios_hasta": 2,
                "dias_otorgados": 14,
                "creado_en": datetime.utcnow(),
                "actualizado_en": datetime.utcnow(),
                "activo": True,
            },
            {
                "anios_desde": 3,
                "anios_hasta": 3,
                "dias_otorgados": 16,
                "creado_en": datetime.utcnow(),
                "actualizado_en": datetime.utcnow(),
                "activo": True,
            },
            {
                "anios_desde": 4,
                "anios_hasta": 4,
                "dias_otorgados": 18,
                "creado_en": datetime.utcnow(),
                "actualizado_en": datetime.utcnow(),
                "activo": True,
            },
            {
                "anios_desde": 5,
                "anios_hasta": 5,
                "dias_otorgados": 20,
                "creado_en": datetime.utcnow(),
                "actualizado_en": datetime.utcnow(),
                "activo": True,
            },
            {
                "anios_desde": 6,
                "anios_hasta": 10,
                "dias_otorgados": 22,
                "creado_en": datetime.utcnow(),
                "actualizado_en": datetime.utcnow(),
                "activo": True,
            },
            {
                "anios_desde": 11,
                "anios_hasta": 15,
                "dias_otorgados": 24,
                "creado_en": datetime.utcnow(),
                "actualizado_en": datetime.utcnow(),
                "activo": True,
            },
            {
                "anios_desde": 16,
                "anios_hasta": 20,
                "dias_otorgados": 26,
                "creado_en": datetime.utcnow(),
                "actualizado_en": datetime.utcnow(),
                "activo": True,
            },
            {
                "anios_desde": 21,
                "anios_hasta": 25,
                "dias_otorgados": 28,
                "creado_en": datetime.utcnow(),
                "actualizado_en": datetime.utcnow(),
                "activo": True,
            },
            {
                "anios_desde": 26,
                "anios_hasta": 30,
                "dias_otorgados": 30,
                "creado_en": datetime.utcnow(),
                "actualizado_en": datetime.utcnow(),
                "activo": True,
            },
        ],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_politicas_vacacionales_id"), table_name="politicas_vacacionales")
    op.drop_table("politicas_vacacionales")
    # ### end Alembic commands ###
