"""Add InfoEmpresa

Revision ID: 859ea593669c
Revises: bd26e214b372
Create Date: 2026-06-07 18:05:31.419021

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "859ea593669c"
down_revision: Union[str, Sequence[str], None] = "bd26e214b372"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "info_empresa",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("mision", sa.String(), nullable=True),
        sa.Column("vision", sa.String(), nullable=True),
        sa.Column("historia", sa.String(), nullable=True),
        sa.Column("valores", sa.JSON(), nullable=True),
        sa.Column("logo_url", sa.String(), nullable=True),
        sa.Column("banner_url", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_info_empresa_id"), "info_empresa", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_info_empresa_id"), table_name="info_empresa")
    op.drop_table("info_empresa")
    # ### end Alembic commands ###
