"""Add matrix reporting and staff roles

Revision ID: b3c6731295a8
Revises: 1f5ce9a03bfd
Create Date: 2026-06-05 02:47:09.590227

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b3c6731295a8"
down_revision: Union[str, Sequence[str], None] = "1f5ce9a03bfd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("puestos", sa.Column("reporta_matricialmente_a_id", sa.Integer(), nullable=True))
    op.add_column(
        "puestos", sa.Column("es_rol_staff", sa.Boolean(), server_default="false", nullable=False)
    )
    op.create_foreign_key(
        "fk_puestos_reporta_matricialmente",
        "puestos",
        "puestos",
        ["reporta_matricialmente_a_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE puestos DROP CONSTRAINT IF EXISTS fk_puestos_reporta_matricialmente")
    op.execute(
        "ALTER TABLE puestos DROP CONSTRAINT IF EXISTS puestos_reporta_matricialmente_a_id_fkey"
    )
    op.drop_column("puestos", "es_rol_staff")
    op.drop_column("puestos", "reporta_matricialmente_a_id")
    # ### end Alembic commands ###
