"""Add RegistroChecador

Revision ID: b4e07eaf3dad
Revises: 58b6ad4a55ba
Create Date: 2026-06-06 14:09:52.537539

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b4e07eaf3dad"
down_revision: Union[str, Sequence[str], None] = "58b6ad4a55ba"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "registros_checador",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("empleado_id", sa.Integer(), nullable=False),
        sa.Column("timestamp_checada", sa.DateTime(), nullable=False),
        sa.Column("metodo", sa.String(length=50), nullable=True),
        sa.Column("dispositivo_ip", sa.String(length=50), nullable=True),
        sa.Column("procesado", sa.Boolean(), nullable=True),
        sa.Column("creado_en", sa.DateTime(), nullable=False),
        sa.Column("actualizado_en", sa.DateTime(), nullable=False),
        sa.Column("activo", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["empleado_id"], ["empleados.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_registros_checador_empleado_id"),
        "registros_checador",
        ["empleado_id"],
        unique=False,
    )
    op.create_index(op.f("ix_registros_checador_id"), "registros_checador", ["id"], unique=False)
    op.create_index(
        op.f("ix_registros_checador_timestamp_checada"),
        "registros_checador",
        ["timestamp_checada"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_registros_checador_timestamp_checada"), table_name="registros_checador")
    op.drop_index(op.f("ix_registros_checador_id"), table_name="registros_checador")
    op.drop_index(op.f("ix_registros_checador_empleado_id"), table_name="registros_checador")
    op.drop_table("registros_checador")
    # ### end Alembic commands ###
