"""create_dispositivos_biometricos_fix

Revision ID: bd26e214b372
Revises: 02d340003dc6
Create Date: 2026-06-06 20:14:52.290413

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bd26e214b372"
down_revision: Union[str, Sequence[str], None] = "02d340003dc6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dispositivos_biometricos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nombre", sa.String(), nullable=True),
        sa.Column(
            "marca",
            sa.Enum("ZKTECO", "HIKVISION", "SUPREMA", "OTRA", name="marcadispositivo"),
            nullable=True,
        ),
        sa.Column(
            "metodo_conexion",
            sa.Enum("PULL_IP", "PUSH_WEBHOOK", name="metodoconexion"),
            nullable=True,
        ),
        sa.Column("ip_address", sa.String(), nullable=True),
        sa.Column("puerto", sa.Integer(), nullable=True),
        sa.Column("token_auth", sa.String(), nullable=True),
        sa.Column("ultima_sincronizacion", sa.DateTime(), nullable=True),
        sa.Column("activo", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_dispositivos_biometricos_id"), "dispositivos_biometricos", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_dispositivos_biometricos_nombre"),
        "dispositivos_biometricos",
        ["nombre"],
        unique=False,
    )
    op.create_index(
        op.f("ix_dispositivos_biometricos_token_auth"),
        "dispositivos_biometricos",
        ["token_auth"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_dispositivos_biometricos_token_auth"), table_name="dispositivos_biometricos"
    )
    op.drop_index(op.f("ix_dispositivos_biometricos_nombre"), table_name="dispositivos_biometricos")
    op.drop_index(op.f("ix_dispositivos_biometricos_id"), table_name="dispositivos_biometricos")
    op.drop_table("dispositivos_biometricos")
    # ### end Alembic commands ###
    op.execute("DROP TYPE IF EXISTS marcadispositivo")
    op.execute("DROP TYPE IF EXISTS metodoconexion")
