"""Esquema Inicial

Revision ID: c059ad856719
Revises:
Create Date: 2026-06-05 00:34:16.724892

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c059ad856719"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "areas",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nombre_area", sa.String(length=50), nullable=False),
        sa.Column("jefe_area_id", sa.Integer(), nullable=True),
        sa.Column("creado_en", sa.DateTime(), nullable=False),
        sa.Column("actualizado_en", sa.DateTime(), nullable=False),
        sa.Column("activo", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["jefe_area_id"],
            ["empleados.id"],
            name="fk_area_jefe",
            ondelete="SET NULL",
            use_alter=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_areas_id"), "areas", ["id"], unique=False)
    op.create_table(
        "conceptos_nomina",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("clave", sa.String(length=20), nullable=False),
        sa.Column("nombre_concepto", sa.String(length=100), nullable=False),
        sa.Column("tipo", sa.String(length=20), nullable=False),
        sa.Column("monto_defecto", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("es_fiscal", sa.Boolean(), nullable=False),
        sa.Column("creado_en", sa.DateTime(), nullable=False),
        sa.Column("actualizado_en", sa.DateTime(), nullable=False),
        sa.Column("activo", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("clave"),
    )
    op.create_index(op.f("ix_conceptos_nomina_id"), "conceptos_nomina", ["id"], unique=False)
    op.create_table(
        "dias_festivos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("fecha", sa.Date(), nullable=False),
        sa.Column("nombre", sa.String(length=255), nullable=False),
        sa.Column("tipo_ley", sa.String(length=100), nullable=False),
        sa.Column("paga_doble", sa.Boolean(), nullable=False),
        sa.Column("nota_ley", sa.String(), nullable=True),
        sa.Column("creado_en", sa.DateTime(), nullable=False),
        sa.Column("actualizado_en", sa.DateTime(), nullable=False),
        sa.Column("activo", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_dias_festivos_id"), "dias_festivos", ["id"], unique=False)
    op.create_table(
        "evaluaciones",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("pregunta", sa.String(), nullable=True),
        sa.Column("tipo_evaluacion", sa.String(length=50), nullable=True),
        sa.Column("creado_en", sa.DateTime(), nullable=False),
        sa.Column("actualizado_en", sa.DateTime(), nullable=False),
        sa.Column("activo", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_evaluaciones_id"), "evaluaciones", ["id"], unique=False)
    op.create_table(
        "recursos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("clave", sa.String(length=50), nullable=False),
        sa.Column("nombre", sa.String(length=100), nullable=False),
        sa.Column("creado_en", sa.DateTime(), nullable=False),
        sa.Column("actualizado_en", sa.DateTime(), nullable=False),
        sa.Column("activo", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("clave"),
    )
    op.create_index(op.f("ix_recursos_id"), "recursos", ["id"], unique=False)
    op.create_table(
        "permisos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("recurso_id", sa.Integer(), nullable=False),
        sa.Column("accion", sa.String(length=50), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("nombre", sa.String(length=100), nullable=False),
        sa.Column("creado_en", sa.DateTime(), nullable=False),
        sa.Column("actualizado_en", sa.DateTime(), nullable=False),
        sa.Column("activo", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["recurso_id"], ["recursos.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_index(op.f("ix_permisos_id"), "permisos", ["id"], unique=False)
    op.create_table(
        "puestos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nombre_puesto", sa.String(length=100), nullable=False),
        sa.Column("descripcion", sa.String(), nullable=True),
        sa.Column("cupo_maximo", sa.Integer(), nullable=False),
        sa.Column("personal_actual", sa.Integer(), nullable=False),
        sa.Column("area_id", sa.Integer(), nullable=True),
        sa.Column("beneficios", sa.String(), nullable=True),
        sa.Column("requisitos", sa.String(), nullable=True),
        sa.Column("sueldo_min", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("sueldo_max", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("creado_en", sa.DateTime(), nullable=False),
        sa.Column("actualizado_en", sa.DateTime(), nullable=False),
        sa.Column("activo", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["area_id"], ["areas.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_puestos_id"), "puestos", ["id"], unique=False)
    op.create_table(
        "roles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nombre_rol", sa.String(length=50), nullable=False),
        sa.Column("descripcion", sa.String(), nullable=True),
        sa.Column("es_sistema", sa.Boolean(), nullable=False),
        sa.Column("nivel_jerarquia", sa.Integer(), nullable=False),
        sa.Column("area_id", sa.Integer(), nullable=True),
        sa.Column("creado_en", sa.DateTime(), nullable=False),
        sa.Column("actualizado_en", sa.DateTime(), nullable=False),
        sa.Column("activo", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["area_id"], ["areas.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_roles_id"), "roles", ["id"], unique=False)
    op.create_table(
        "empleados",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nombre_completo", sa.String(length=255), nullable=False),
        sa.Column("curp", sa.String(length=18), nullable=True),
        sa.Column("rfc", sa.String(length=13), nullable=True),
        sa.Column("email", sa.String(length=50), nullable=True),
        sa.Column("telefono", sa.String(length=12), nullable=True),
        sa.Column("direccion", sa.String(length=255), nullable=True),
        sa.Column("fecha_ingreso", sa.Date(), nullable=True),
        sa.Column("estatus", sa.String(length=15), nullable=False),
        sa.Column("dias_vacaciones_disponibles", sa.Integer(), nullable=False),
        sa.Column("sueldo", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("sueldo_fiscal", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("infonavit_mensual", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("fondo_ahorro_pct", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("vales_despensa_pct", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("foto", sa.String(), nullable=True),
        sa.Column("ciudad", sa.String(length=100), nullable=True),
        sa.Column("colonia", sa.String(length=100), nullable=True),
        sa.Column("cp", sa.String(length=10), nullable=True),
        sa.Column("entidad_federativa", sa.String(length=100), nullable=True),
        sa.Column("estado_civil", sa.String(length=30), nullable=True),
        sa.Column("fecha_nacimiento", sa.Date(), nullable=True),
        sa.Column("lugar_nacimiento", sa.String(length=100), nullable=True),
        sa.Column("sexo", sa.String(length=10), nullable=True),
        sa.Column("ultimo_grado_escolar", sa.String(length=50), nullable=True),
        sa.Column("cartilla_militar", sa.Boolean(), nullable=False),
        sa.Column("aspiraciones_profesionales", sa.String(), nullable=True),
        sa.Column("rol_id", sa.Integer(), nullable=True),
        sa.Column("area_id", sa.Integer(), nullable=True),
        sa.Column("puesto_id", sa.Integer(), nullable=True),
        sa.Column("jefe_directo_id", sa.Integer(), nullable=True),
        sa.Column("creado_en", sa.DateTime(), nullable=False),
        sa.Column("actualizado_en", sa.DateTime(), nullable=False),
        sa.Column("activo", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["area_id"], ["areas.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["jefe_directo_id"], ["empleados.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["puesto_id"], ["puestos.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["rol_id"], ["roles.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_empleados_email"), "empleados", ["email"], unique=True)
    op.create_index(op.f("ix_empleados_id"), "empleados", ["id"], unique=False)
    op.create_table(
        "permisos_campo",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("rol_id", sa.Integer(), nullable=False),
        sa.Column("clave_recurso", sa.String(length=50), nullable=False),
        sa.Column("clave_campo", sa.String(length=50), nullable=False),
        sa.Column("puede_leer", sa.Boolean(), nullable=False),
        sa.Column("puede_escribir", sa.Boolean(), nullable=False),
        sa.Column("creado_en", sa.DateTime(), nullable=False),
        sa.Column("actualizado_en", sa.DateTime(), nullable=False),
        sa.Column("activo", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["rol_id"], ["roles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_permisos_campo_id"), "permisos_campo", ["id"], unique=False)
    op.create_table(
        "rol_permisos",
        sa.Column("rol_id", sa.Integer(), nullable=False),
        sa.Column("permiso_id", sa.Integer(), nullable=False),
        sa.Column("alcance", sa.String(length=20), nullable=False),
        sa.Column("creado_en", sa.DateTime(), nullable=False),
        sa.Column("actualizado_en", sa.DateTime(), nullable=False),
        sa.Column("activo", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["permiso_id"], ["permisos.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["rol_id"], ["roles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("rol_id", "permiso_id"),
    )
    op.create_table(
        "vacantes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("titulo", sa.String(length=100), nullable=False),
        sa.Column("descripcion", sa.String(), nullable=True),
        sa.Column("area_id", sa.Integer(), nullable=True),
        sa.Column("rol_id", sa.Integer(), nullable=True),
        sa.Column("puesto_id", sa.Integer(), nullable=True),
        sa.Column("cantidad_solicitada", sa.Integer(), nullable=False),
        sa.Column("cantidad_contratada", sa.Integer(), nullable=False),
        sa.Column("estatus", sa.String(length=20), nullable=False),
        sa.Column("creado_en", sa.DateTime(), nullable=False),
        sa.Column("actualizado_en", sa.DateTime(), nullable=False),
        sa.Column("activo", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["area_id"], ["areas.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["puesto_id"], ["puestos.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["rol_id"], ["roles.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_vacantes_id"), "vacantes", ["id"], unique=False)
    op.create_table(
        "asistencias",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("empleado_id", sa.Integer(), nullable=False),
        sa.Column("fecha", sa.Date(), nullable=False),
        sa.Column("hora_entrada", sa.String(length=5), nullable=True),
        sa.Column("hora_salida", sa.String(length=5), nullable=True),
        sa.Column("tipo", sa.String(length=20), nullable=False),
        sa.Column("justificacion", sa.String(), nullable=True),
        sa.Column("registrado_por_id", sa.Integer(), nullable=True),
        sa.Column("creado_en", sa.DateTime(), nullable=False),
        sa.Column("actualizado_en", sa.DateTime(), nullable=False),
        sa.Column("activo", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["empleado_id"], ["empleados.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["registrado_por_id"], ["empleados.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_asistencias_empleado_id"), "asistencias", ["empleado_id"], unique=False
    )
    op.create_index(op.f("ix_asistencias_fecha"), "asistencias", ["fecha"], unique=False)
    op.create_index(op.f("ix_asistencias_id"), "asistencias", ["id"], unique=False)
    op.create_table(
        "candidatos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nombre_completo", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=100), nullable=True),
        sa.Column("telefono", sa.String(length=20), nullable=True),
        sa.Column("cv_url", sa.String(), nullable=True),
        sa.Column("vacante_id", sa.Integer(), nullable=True),
        sa.Column("puesto_id", sa.Integer(), nullable=True),
        sa.Column("estatus", sa.String(length=20), nullable=False),
        sa.Column("notas", sa.String(), nullable=True),
        sa.Column("creado_en", sa.DateTime(), nullable=False),
        sa.Column("actualizado_en", sa.DateTime(), nullable=False),
        sa.Column("activo", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["puesto_id"], ["puestos.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["vacante_id"], ["vacantes.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_candidatos_id"), "candidatos", ["id"], unique=False)
    op.create_table(
        "conversaciones",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nombre", sa.String(length=255), nullable=True),
        sa.Column("tipo", sa.String(length=50), nullable=False),
        sa.Column("creado_por_id", sa.Integer(), nullable=True),
        sa.Column("creado_en", sa.DateTime(), nullable=False),
        sa.Column("actualizado_en", sa.DateTime(), nullable=False),
        sa.Column("activo", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["creado_por_id"], ["empleados.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_conversaciones_id"), "conversaciones", ["id"], unique=False)
    op.create_table(
        "credenciales",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("empleado_id", sa.Integer(), nullable=False),
        sa.Column("nombre_usuario", sa.String(length=50), nullable=False),
        sa.Column("contrasena_hasheada", sa.String(), nullable=False),
        sa.Column("requiere_cambio_contrasena", sa.Boolean(), nullable=False),
        sa.Column("creado_en", sa.DateTime(), nullable=False),
        sa.Column("actualizado_en", sa.DateTime(), nullable=False),
        sa.Column("activo", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["empleado_id"], ["empleados.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("empleado_id"),
    )
    op.create_index(op.f("ix_credenciales_id"), "credenciales", ["id"], unique=False)
    op.create_index(
        op.f("ix_credenciales_nombre_usuario"), "credenciales", ["nombre_usuario"], unique=True
    )
    op.create_table(
        "delegacion_roles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("delegador_id", sa.Integer(), nullable=False),
        sa.Column("delegado_id", sa.Integer(), nullable=False),
        sa.Column("rol_id", sa.Integer(), nullable=False),
        sa.Column("estatus", sa.String(length=20), nullable=False),
        sa.Column("creado_en", sa.DateTime(), nullable=False),
        sa.Column("actualizado_en", sa.DateTime(), nullable=False),
        sa.Column("activo", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["delegado_id"], ["empleados.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["delegador_id"], ["empleados.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["rol_id"], ["roles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_delegacion_roles_id"), "delegacion_roles", ["id"], unique=False)
    op.create_table(
        "empleado_permisos",
        sa.Column("empleado_id", sa.Integer(), nullable=False),
        sa.Column("permiso_id", sa.Integer(), nullable=False),
        sa.Column("alcance", sa.String(length=20), nullable=False),
        sa.Column("concedido", sa.Boolean(), nullable=False),
        sa.Column("creado_en", sa.DateTime(), nullable=False),
        sa.Column("actualizado_en", sa.DateTime(), nullable=False),
        sa.Column("activo", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["empleado_id"], ["empleados.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["permiso_id"], ["permisos.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("empleado_id", "permiso_id"),
    )
    op.create_table(
        "empleados_familiar",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("empleado_id", sa.Integer(), nullable=False),
        sa.Column("nombre_completo", sa.String(length=255), nullable=True),
        sa.Column("telefono", sa.String(length=12), nullable=True),
        sa.Column("email", sa.String(length=50), nullable=True),
        sa.Column("direccion", sa.String(length=255), nullable=True),
        sa.Column("parentesco", sa.String(length=30), nullable=True),
        sa.Column("creado_en", sa.DateTime(), nullable=False),
        sa.Column("actualizado_en", sa.DateTime(), nullable=False),
        sa.Column("activo", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["empleado_id"], ["empleados.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_empleados_familiar_empleado_id"),
        "empleados_familiar",
        ["empleado_id"],
        unique=False,
    )
    op.create_index(op.f("ix_empleados_familiar_id"), "empleados_familiar", ["id"], unique=False)
    op.create_table(
        "empleados_salud",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("empleado_id", sa.Integer(), nullable=False),
        sa.Column("discapacidad", sa.Boolean(), nullable=False),
        sa.Column("desc_disc", sa.String(), nullable=True),
        sa.Column("condicion", sa.Boolean(), nullable=False),
        sa.Column("desc_cond", sa.String(), nullable=True),
        sa.Column("tipo_sangre", sa.String(length=10), nullable=True),
        sa.Column("nss", sa.String(length=11), nullable=True),
        sa.Column("creado_en", sa.DateTime(), nullable=False),
        sa.Column("actualizado_en", sa.DateTime(), nullable=False),
        sa.Column("activo", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["empleado_id"], ["empleados.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("empleado_id"),
    )
    op.create_index(op.f("ix_empleados_salud_id"), "empleados_salud", ["id"], unique=False)
    op.create_table(
        "encuesta_clima",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("empleado_id", sa.Integer(), nullable=True),
        sa.Column("nivel_jerarquico", sa.String(length=50), nullable=True),
        sa.Column("ubicacion", sa.String(length=50), nullable=True),
        sa.Column("hijos", sa.String(length=20), nullable=True),
        sa.Column("antiguedad", sa.String(length=20), nullable=True),
        sa.Column("genero", sa.String(length=20), nullable=True),
        sa.Column("orientacion_org", sa.JSON(), nullable=True),
        sa.Column("admin_talento", sa.JSON(), nullable=True),
        sa.Column("estilo_direccion", sa.JSON(), nullable=True),
        sa.Column("comunicacion_int", sa.JSON(), nullable=True),
        sa.Column("trabajo_equipo", sa.JSON(), nullable=True),
        sa.Column("capacidad_prof", sa.JSON(), nullable=True),
        sa.Column("medio_ambiente", sa.JSON(), nullable=True),
        sa.Column("creado_en", sa.DateTime(), nullable=False),
        sa.Column("actualizado_en", sa.DateTime(), nullable=False),
        sa.Column("activo", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["empleado_id"], ["empleados.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("empleado_id"),
    )
    op.create_index(op.f("ix_encuesta_clima_id"), "encuesta_clima", ["id"], unique=False)
    op.create_table(
        "eventos_empresa",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("titulo", sa.String(length=200), nullable=False),
        sa.Column("descripcion", sa.String(), nullable=True),
        sa.Column("fecha_inicio", sa.Date(), nullable=False),
        sa.Column("fecha_fin", sa.Date(), nullable=False),
        sa.Column("hora_inicio", sa.String(length=5), nullable=True),
        sa.Column("hora_fin", sa.String(length=5), nullable=True),
        sa.Column("tipo", sa.String(length=50), nullable=False),
        sa.Column("color", sa.String(length=7), nullable=True),
        sa.Column("creado_por_id", sa.Integer(), nullable=True),
        sa.Column("creado_en", sa.DateTime(), nullable=False),
        sa.Column("actualizado_en", sa.DateTime(), nullable=False),
        sa.Column("activo", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["creado_por_id"], ["empleados.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_eventos_empresa_id"), "eventos_empresa", ["id"], unique=False)
    op.create_table(
        "incidencias",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("empleado_reportado_id", sa.Integer(), nullable=False),
        sa.Column("reportante_id", sa.Integer(), nullable=True),
        sa.Column("titulo", sa.String(length=150), nullable=True),
        sa.Column("descripcion", sa.String(), nullable=True),
        sa.Column("tipo", sa.String(length=50), nullable=True),
        sa.Column("gravedad", sa.String(length=20), nullable=True),
        sa.Column("estatus", sa.String(length=20), nullable=False),
        sa.Column("fecha_incidencia", sa.Date(), nullable=True),
        sa.Column("evidencia_url", sa.String(), nullable=True),
        sa.Column("creado_en", sa.DateTime(), nullable=False),
        sa.Column("actualizado_en", sa.DateTime(), nullable=False),
        sa.Column("activo", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["empleado_reportado_id"], ["empleados.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["reportante_id"], ["empleados.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_incidencias_id"), "incidencias", ["id"], unique=False)
    op.create_table(
        "lotes_nomina",
        sa.Column("id", sa.String(length=50), nullable=False),
        sa.Column("periodo_inicio", sa.Date(), nullable=False),
        sa.Column("periodo_fin", sa.Date(), nullable=False),
        sa.Column("tipo_nomina", sa.String(length=20), nullable=True),
        sa.Column("total_lote", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column("estatus", sa.String(length=20), nullable=False),
        sa.Column("creado_por_id", sa.Integer(), nullable=True),
        sa.Column("creado_en", sa.DateTime(), nullable=False),
        sa.Column("actualizado_en", sa.DateTime(), nullable=False),
        sa.Column("activo", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["creado_por_id"], ["empleados.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "notificaciones",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("empleado_id", sa.Integer(), nullable=True),
        sa.Column("titulo", sa.String(length=100), nullable=False),
        sa.Column("mensaje", sa.String(), nullable=False),
        sa.Column("tipo", sa.String(length=50), nullable=False),
        sa.Column("leida", sa.Boolean(), nullable=False),
        sa.Column("link", sa.String(length=255), nullable=True),
        sa.Column("creado_en", sa.DateTime(), nullable=False),
        sa.Column("actualizado_en", sa.DateTime(), nullable=False),
        sa.Column("activo", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["empleado_id"], ["empleados.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_notificaciones_empleado_id"), "notificaciones", ["empleado_id"], unique=False
    )
    op.create_index(op.f("ix_notificaciones_id"), "notificaciones", ["id"], unique=False)
    op.create_table(
        "prestamos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("empleado_id", sa.Integer(), nullable=False),
        sa.Column("monto_total", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("saldo_pendiente", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("abono_periodo", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("estatus", sa.String(length=20), nullable=False),
        sa.Column("notas", sa.String(), nullable=True),
        sa.Column("creado_en", sa.DateTime(), nullable=False),
        sa.Column("actualizado_en", sa.DateTime(), nullable=False),
        sa.Column("activo", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["empleado_id"], ["empleados.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_prestamos_empleado_id"), "prestamos", ["empleado_id"], unique=False)
    op.create_index(op.f("ix_prestamos_id"), "prestamos", ["id"], unique=False)
    op.create_table(
        "respuestas_evaluacion",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("pregunta_id", sa.Integer(), nullable=False),
        sa.Column("empleado_id", sa.Integer(), nullable=False),
        sa.Column("respuesta", sa.String(), nullable=True),
        sa.Column("creado_en", sa.DateTime(), nullable=False),
        sa.Column("actualizado_en", sa.DateTime(), nullable=False),
        sa.Column("activo", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["empleado_id"], ["empleados.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["pregunta_id"], ["evaluaciones.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_respuestas_evaluacion_id"), "respuestas_evaluacion", ["id"], unique=False
    )
    op.create_table(
        "tareas",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("empleado_id", sa.Integer(), nullable=False),
        sa.Column("asignado_por_id", sa.Integer(), nullable=True),
        sa.Column("titulo", sa.String(length=255), nullable=False),
        sa.Column("descripcion", sa.String(), nullable=True),
        sa.Column("prioridad", sa.String(length=20), nullable=False),
        sa.Column("fecha_vencimiento", sa.Date(), nullable=True),
        sa.Column("completada", sa.Boolean(), nullable=False),
        sa.Column("creado_en", sa.DateTime(), nullable=False),
        sa.Column("actualizado_en", sa.DateTime(), nullable=False),
        sa.Column("activo", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["asignado_por_id"], ["empleados.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["empleado_id"], ["empleados.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tareas_id"), "tareas", ["id"], unique=False)
    op.create_table(
        "vacaciones",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("empleado_id", sa.Integer(), nullable=False),
        sa.Column("fecha_inicio", sa.Date(), nullable=False),
        sa.Column("fecha_fin", sa.Date(), nullable=False),
        sa.Column("estatus_vacacion", sa.String(length=20), nullable=False),
        sa.Column("tipo_solicitud", sa.String(length=50), nullable=False),
        sa.Column("motivo", sa.String(), nullable=True),
        sa.Column("motivo_rechazo", sa.String(), nullable=True),
        sa.Column("creado_en", sa.DateTime(), nullable=False),
        sa.Column("actualizado_en", sa.DateTime(), nullable=False),
        sa.Column("activo", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["empleado_id"], ["empleados.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_vacaciones_empleado_id"), "vacaciones", ["empleado_id"], unique=False)
    op.create_index(op.f("ix_vacaciones_id"), "vacaciones", ["id"], unique=False)
    op.create_table(
        "conversacion_participantes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("conversacion_id", sa.Integer(), nullable=False),
        sa.Column("empleado_id", sa.Integer(), nullable=False),
        sa.Column("creado_en", sa.DateTime(), nullable=False),
        sa.Column("actualizado_en", sa.DateTime(), nullable=False),
        sa.Column("activo", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["conversacion_id"], ["conversaciones.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["empleado_id"], ["empleados.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_conversacion_participantes_id"), "conversacion_participantes", ["id"], unique=False
    )
    op.create_table(
        "cyi_progreso",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("candidato_id", sa.Integer(), nullable=True),
        sa.Column("empleado_id", sa.Integer(), nullable=True),
        sa.Column("etapa_id", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("items", sa.JSON(), nullable=False),
        sa.Column("notas", sa.String(), nullable=True),
        sa.Column("creado_en", sa.DateTime(), nullable=False),
        sa.Column("actualizado_en", sa.DateTime(), nullable=False),
        sa.Column("activo", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["candidato_id"], ["candidatos.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["empleado_id"], ["empleados.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_cyi_progreso_candidato_id"), "cyi_progreso", ["candidato_id"], unique=False
    )
    op.create_index(
        op.f("ix_cyi_progreso_empleado_id"), "cyi_progreso", ["empleado_id"], unique=False
    )
    op.create_index(op.f("ix_cyi_progreso_etapa_id"), "cyi_progreso", ["etapa_id"], unique=False)
    op.create_index(op.f("ix_cyi_progreso_id"), "cyi_progreso", ["id"], unique=False)
    op.create_table(
        "evento_participantes",
        sa.Column("evento_id", sa.Integer(), nullable=False),
        sa.Column("empleado_id", sa.Integer(), nullable=False),
        sa.Column("creado_en", sa.DateTime(), nullable=False),
        sa.Column("actualizado_en", sa.DateTime(), nullable=False),
        sa.Column("activo", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["empleado_id"], ["empleados.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["evento_id"], ["eventos_empresa.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("evento_id", "empleado_id"),
    )
    op.create_table(
        "mensajes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("conversacion_id", sa.Integer(), nullable=False),
        sa.Column("emisor_id", sa.Integer(), nullable=True),
        sa.Column("contenido", sa.String(), nullable=False),
        sa.Column("leido", sa.Boolean(), nullable=False),
        sa.Column("creado_en", sa.DateTime(), nullable=False),
        sa.Column("actualizado_en", sa.DateTime(), nullable=False),
        sa.Column("activo", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["conversacion_id"], ["conversaciones.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["emisor_id"], ["empleados.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_mensajes_conversacion_id"), "mensajes", ["conversacion_id"], unique=False
    )
    op.create_index(op.f("ix_mensajes_id"), "mensajes", ["id"], unique=False)
    op.create_table(
        "nominas",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("empleado_id", sa.Integer(), nullable=False),
        sa.Column("lote_id", sa.String(length=50), nullable=True),
        sa.Column("fecha_inicio", sa.Date(), nullable=False),
        sa.Column("fecha_fin", sa.Date(), nullable=False),
        sa.Column("sueldo_base", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("bonos", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("deducciones", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("total_pagado", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("metodo_pago", sa.String(length=50), nullable=True),
        sa.Column("estado", sa.String(length=20), nullable=False),
        sa.Column("monto_reportado_fiscal", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("monto_variacion_complemento", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("dias_trabajados", sa.Integer(), nullable=False),
        sa.Column("sdi", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("factor_integracion", sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column("costo_patronal", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("certificado_sat", sa.String(), nullable=True),
        sa.Column("estatus_sat", sa.String(length=50), nullable=False),
        sa.Column("pdf_url", sa.String(), nullable=True),
        sa.Column("sello_sat", sa.String(), nullable=True),
        sa.Column("uuid_sat", sa.String(length=100), nullable=True),
        sa.Column("xml_url", sa.String(), nullable=True),
        sa.Column("creado_en", sa.DateTime(), nullable=False),
        sa.Column("actualizado_en", sa.DateTime(), nullable=False),
        sa.Column("activo", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["empleado_id"], ["empleados.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["lote_id"], ["lotes_nomina.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_nominas_empleado_id"), "nominas", ["empleado_id"], unique=False)
    op.create_index(op.f("ix_nominas_id"), "nominas", ["id"], unique=False)
    op.create_index(op.f("ix_nominas_lote_id"), "nominas", ["lote_id"], unique=False)
    op.create_table(
        "detalles_nomina",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nomina_id", sa.Integer(), nullable=False),
        sa.Column("concepto_id", sa.Integer(), nullable=False),
        sa.Column("monto_aplicado", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("creado_en", sa.DateTime(), nullable=False),
        sa.Column("actualizado_en", sa.DateTime(), nullable=False),
        sa.Column("activo", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["concepto_id"], ["conceptos_nomina.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["nomina_id"], ["nominas.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_detalles_nomina_concepto_id"), "detalles_nomina", ["concepto_id"], unique=False
    )
    op.create_index(op.f("ix_detalles_nomina_id"), "detalles_nomina", ["id"], unique=False)
    op.create_index(
        op.f("ix_detalles_nomina_nomina_id"), "detalles_nomina", ["nomina_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_detalles_nomina_nomina_id"), table_name="detalles_nomina")
    op.drop_index(op.f("ix_detalles_nomina_id"), table_name="detalles_nomina")
    op.drop_index(op.f("ix_detalles_nomina_concepto_id"), table_name="detalles_nomina")
    op.drop_table("detalles_nomina")
    op.drop_index(op.f("ix_nominas_lote_id"), table_name="nominas")
    op.drop_index(op.f("ix_nominas_id"), table_name="nominas")
    op.drop_index(op.f("ix_nominas_empleado_id"), table_name="nominas")
    op.drop_table("nominas")
    op.drop_index(op.f("ix_mensajes_id"), table_name="mensajes")
    op.drop_index(op.f("ix_mensajes_conversacion_id"), table_name="mensajes")
    op.drop_table("mensajes")
    op.drop_table("evento_participantes")
    op.drop_index(op.f("ix_cyi_progreso_id"), table_name="cyi_progreso")
    op.drop_index(op.f("ix_cyi_progreso_etapa_id"), table_name="cyi_progreso")
    op.drop_index(op.f("ix_cyi_progreso_empleado_id"), table_name="cyi_progreso")
    op.drop_index(op.f("ix_cyi_progreso_candidato_id"), table_name="cyi_progreso")
    op.drop_table("cyi_progreso")
    op.drop_index(op.f("ix_conversacion_participantes_id"), table_name="conversacion_participantes")
    op.drop_table("conversacion_participantes")
    op.drop_index(op.f("ix_vacaciones_id"), table_name="vacaciones")
    op.drop_index(op.f("ix_vacaciones_empleado_id"), table_name="vacaciones")
    op.drop_table("vacaciones")
    op.drop_index(op.f("ix_tareas_id"), table_name="tareas")
    op.drop_table("tareas")
    op.drop_index(op.f("ix_respuestas_evaluacion_id"), table_name="respuestas_evaluacion")
    op.drop_table("respuestas_evaluacion")
    op.drop_index(op.f("ix_prestamos_id"), table_name="prestamos")
    op.drop_index(op.f("ix_prestamos_empleado_id"), table_name="prestamos")
    op.drop_table("prestamos")
    op.drop_index(op.f("ix_notificaciones_id"), table_name="notificaciones")
    op.drop_index(op.f("ix_notificaciones_empleado_id"), table_name="notificaciones")
    op.drop_table("notificaciones")
    op.drop_table("lotes_nomina")
    op.drop_index(op.f("ix_incidencias_id"), table_name="incidencias")
    op.drop_table("incidencias")
    op.drop_index(op.f("ix_eventos_empresa_id"), table_name="eventos_empresa")
    op.drop_table("eventos_empresa")
    op.drop_index(op.f("ix_encuesta_clima_id"), table_name="encuesta_clima")
    op.drop_table("encuesta_clima")
    op.drop_index(op.f("ix_empleados_salud_id"), table_name="empleados_salud")
    op.drop_table("empleados_salud")
    op.drop_index(op.f("ix_empleados_familiar_id"), table_name="empleados_familiar")
    op.drop_index(op.f("ix_empleados_familiar_empleado_id"), table_name="empleados_familiar")
    op.drop_table("empleados_familiar")
    op.drop_table("empleado_permisos")
    op.drop_index(op.f("ix_delegacion_roles_id"), table_name="delegacion_roles")
    op.drop_table("delegacion_roles")
    op.drop_index(op.f("ix_credenciales_nombre_usuario"), table_name="credenciales")
    op.drop_index(op.f("ix_credenciales_id"), table_name="credenciales")
    op.drop_table("credenciales")
    op.drop_index(op.f("ix_conversaciones_id"), table_name="conversaciones")
    op.drop_table("conversaciones")
    op.drop_index(op.f("ix_candidatos_id"), table_name="candidatos")
    op.drop_table("candidatos")
    op.drop_index(op.f("ix_asistencias_id"), table_name="asistencias")
    op.drop_index(op.f("ix_asistencias_fecha"), table_name="asistencias")
    op.drop_index(op.f("ix_asistencias_empleado_id"), table_name="asistencias")
    op.drop_table("asistencias")
    op.drop_index(op.f("ix_vacantes_id"), table_name="vacantes")
    op.drop_table("vacantes")
    op.drop_table("rol_permisos")
    op.drop_index(op.f("ix_permisos_campo_id"), table_name="permisos_campo")
    op.drop_table("permisos_campo")
    op.drop_index(op.f("ix_empleados_id"), table_name="empleados")
    op.drop_index(op.f("ix_empleados_email"), table_name="empleados")
    op.drop_table("empleados")
    op.drop_index(op.f("ix_roles_id"), table_name="roles")
    op.drop_table("roles")
    op.drop_index(op.f("ix_puestos_id"), table_name="puestos")
    op.drop_table("puestos")
    op.drop_index(op.f("ix_permisos_id"), table_name="permisos")
    op.drop_table("permisos")
    op.drop_index(op.f("ix_recursos_id"), table_name="recursos")
    op.drop_table("recursos")
    op.drop_index(op.f("ix_evaluaciones_id"), table_name="evaluaciones")
    op.drop_table("evaluaciones")
    op.drop_index(op.f("ix_dias_festivos_id"), table_name="dias_festivos")
    op.drop_table("dias_festivos")
    op.drop_index(op.f("ix_conceptos_nomina_id"), table_name="conceptos_nomina")
    op.drop_table("conceptos_nomina")
    op.drop_index(op.f("ix_areas_id"), table_name="areas")
    op.drop_table("areas")
    # ### end Alembic commands ###
