"""Add auditoria_logs table

Revision ID: d4e2020b04be
Revises: 26eefb55c8d9
Create Date: 2026-06-16 04:35:31.039737

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d4e2020b04be"
down_revision: Union[str, Sequence[str], None] = "26eefb55c8d9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "auditoria_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tabla_afectada", sa.String(length=100), nullable=False),
        sa.Column("registro_id", sa.Integer(), nullable=False),
        sa.Column("accion", sa.String(length=20), nullable=False),
        sa.Column("cambios", sa.JSON(), nullable=True),
        sa.Column("realizado_por_id", sa.Integer(), nullable=True),
        sa.Column("creado_en", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_auditoria_logs_id"), "auditoria_logs", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_auditoria_logs_id"), table_name="auditoria_logs")
    op.drop_table("auditoria_logs")
    # ### end Alembic commands ###
