"""Add es_sistema to Empleado

Revision ID: e9d26e2f7b4e
Revises: 2950dcd992f6
Create Date: 2026-06-13 15:44:51.170726

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e9d26e2f7b4e"
down_revision: Union[str, Sequence[str], None] = "2950dcd992f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "empleados", sa.Column("es_sistema", sa.Boolean(), server_default="false", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("empleados", "es_sistema")
    # ### end Alembic commands ###
